services:
  ai-video-transcriber:
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "${PORT:-8893}:${PORT:-8893}"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - WHISPER_MODEL_SIZE=${WHISPER_MODEL_SIZE:-tiny}
      - HOST=0.0.0.0
      - PORT=${PORT:-8893}
    volumes:
      - .:/app
    restart: unless-stopped
    command: ["python3", "start.py", "--prod"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
