services:
  ai-video-transcriber:
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "${PORT:-8893}:${PORT:-8893}"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    command: ["python3", "start.py", "--prod"]
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:${PORT:-8893}/health && nvidia-smi > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
